services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
    volumes:
      - ./conf/nginx/:/config/nginx/
    networks:
      - proxy-tier

  pretalx:
    image: pretalx/standalone:latest
    container_name: pretalx
    restart: unless-stopped
    depends_on:
      - redis
      - db
    environment:
      PRETALX_FILESYSTEM_MEDIA: ${PRETALX_FILESYSTEM_MEDIA}
      PRETALX_FILESYSTEM_STATIC: ${PRETALX_FILESYSTEM_STATIC}
    expose:
      - "80"
    volumes:
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data
      - pretalx-public:/public
    networks:
      - proxy-tier
      - default

  db:
    image: docker.io/library/postgres:15-alpine
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes:
      - pretalx-redis:/data
    networks:
      - default

volumes:
  pretalx-database:
  pretalx-data:
  pretalx-public:
  pretalx-redis:

networks:
  proxy-tier:
    driver: bridge
  default:
    driver: bridge
